name: Convert Jupyter Notebooks to Python Scripts

on:
  push:
  workflow_dispatch:
jobs:
  convert_notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Jupytext
      run: pip install jupytext black

    - name: Convert notebooks to formatted Python scripts
      run: |
        for notebook in $(find . -name "*.ipynb"); do
          jupytext --to py:percent "$notebook"
          py_file="${notebook%.ipynb}.py"
          if [ -f "$py_file" ]; then
            black --line-length 120 "$py_file"
          fi
        done

    - name: Commit changes
      run: |
        var="$(git log -1 --pretty=%B)"
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "nb2py: $var"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}